# Generated by Django 5.2.14 on 2026-06-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrapedLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("website_url", models.URLField(blank=True, max_length=500, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("industry", models.CharField(max_length=255)),
                ("description_summary", models.TextField()),
                (
                    "qualification_score",
                    models.CharField(
                        choices=[
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "pipeline_status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Contacted", "Contacted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="New",
                        max_length=20,
                    ),
                ),
                ("reasoning", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
